---
title: "Time record"
author: "Samantha Shang"
date: "6/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#options("install.lock"=FALSE)

Packages <- c("tidyverse", "lavaan","qualtRics","here", "openssl",
              "readxl", "purrr", "dplyr", "Hmisc", "daff", "lubridate")

#if ( !require(.package) ) install.packages(.package)

lapply(Packages, library, character.only = TRUE)

path <- setwd("S:/Data")

```



```{r create table}


blank_timesheet <- data.frame(
  Title = character(),
  Year = numeric(),
  Month = character(),
  Research = double(),
  Work = double(),
  School = double(),
  Total = double(),
  Workdays = integer()
)


convert_to_hours <- function()

    
apr_2021 <- add_var_table %>%
  mutate( var_cat = case_when(
    add_var_list %in% weight_list ~ "weight",
    add_var_list %in% condition_var_list ~ "condition",
    add_var_list %in% fs_list ~ "factor") ) %>%
  rename(master_item_num = add_var_list) %>%
  mutate(item_text = NA_character_) %>%
  mutate(scale_note = NA_character_) %>%
  mutate(wba_default_2019 = NA_character_) %>%
  mutate(wba_default_spring_2020 = NA_character_) %>%
  mutate(wba_default_fall_2020 = NA_character_) %>%
  mutate(var_order = row_number()) %>%
  subset(select = c(var_cat, master_item_num, item_text, scale_note,
                    wba_default_2019, wba_default_spring_2020,
                    wba_default_fall_2020,
                    var_order))

      
new_record <- rbind(current_record, apr_2021)      




```



